easy_admin:
  entities:
    # List the entity class name you want to manage
    Tournoi:
      class: App\Entity\Tournoi
      form:
        fields:
          - {property: date_debut_tournoi}
          - {property: date_fin_tournoi }

      list:
        fields:
          - {property: saison, label: 'Saison'}
          - {property: nbre_match, label: 'Nombre de match'}
          - {property: date_debut_tournoi, label: 'Date de début de tournoi'}
          - {property: date_fin_tournoi,label: 'Date de fin de tournoi'}
