easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: 'Utilisateur'
      disabled_actions: ['new','delete']
      list:
        fields:
          - {property: 'username' ,label: "Nom d'utilisateur"}
          - {property: 'email', label: 'Email'}
          - {property: 'enable', label: 'Activé'}
          - {property: 'roles', label: 'Role'}

      form:
        fields:
          - {property: 'username' ,label: "Nom d'utilisateur"}
          - {property: 'email', label: 'Email'}
          - {property: 'enable', label: 'Activé'}
          - {property: 'roles', label: 'Role'}

